### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Artis84** [dfaker/WebmGenerator#10]
Hi 

I have this error when i launch the program
![Capture du 2020-08-24 08-31-23](https://user-images.githubusercontent.com/45531582/91064536-3902a400-e5e4-11ea-9d04-f95823cca862.png)

I dont understand

**Comment by dfaker** [comment]
You'll need to install tkinter too if it's not already present:

`sudo apt-get update
sudo apt-get install python3-tk`

**Comment by Artis84** [comment]
It's work but now i have this error:
![Capture du 2020-08-24 12-13-54](https://user-images.githubusercontent.com/45531582/91086198-70cd1400-e603-11ea-84fd-a8d6cb10b46b.png)

**Comment by dfaker** [comment]
You'll also need to apt-install the most recent ffmpeg and libmpv

**Comment by Artis84** [comment]
Thanks
