### ISSUE TITLE
Subclips naming and other requests

### ISSUE THREAD

**Issue by 30secstf** [dfaker/WebmGenerator#100]
- As spoken elsewhere, for my specific workflow it would be handy to be able to set names for the subclips and have that name appended to the final file name on saving the final encodes, so it's easy to identify what is what and speed up the archiving. Maybe as a right click mouse menu option?
- I'd also like to resize the subclips already in place with a given time length. Es. resize a 30 seconds subclip to 20 seconds (or 40), ideally with three option: peel off  (or add) the specified length at subclip start, end and centered. PS: there's an "Edit subclip" menu entry but it seems not doing anything.
- Software H265 HEVC encoder?
- The Stream Copy merge style would be sometimes useful but it produce corrupted files :(
- More often than I'd like WmG has to re-encode because File too large, this happens more often with longer (more than a minute long) subclips. Surely I have messed with "allowableTargetSizeUnderrun" but it happens also with default setting.
- When "Loading Image as static video" please add an example of the format of the time frame to be inserted at the prompt: I do it every once in a while and I keep forgetting how to properly type it : ) (should be total seconds, IIRC).

Sorry for many requests and thank you for WebmGenerator!

**Comment by dfaker** [comment]
~~When "Loading Image as static video" please add an example of the format of the time frame to be inserted at the prompt: I do it every once in a while and I keep forgetting how to properly type it : ) (should be total seconds, IIRC).~~

**Comment by dfaker** [comment]
~I'd also like to resize the subclips already in place with a given time length. Es. resize a 30 seconds subclip to 20 seconds (or 40), ideally with three option: peel off (or add) the specified length at subclip start, end and centered. PS: there's an "Edit subclip" menu entry but it seems not doing anything.~

**Comment by dfaker** [comment]
~As spoken elsewhere, for my specific workflow it would be handy to be able to set names for the subclips and have that name appended to the final file name on saving the final encodes, so it's easy to identify what is what and speed up the archiving. Maybe as a right click mouse menu option?~

**Comment by dfaker** [comment]
~Software H265 HEVC encoder?~

**Comment by dfaker** [comment]
@30secstf updated in most recent build now.

**Comment by 30secstf** [comment]
> @30secstf updated in most recent build now.

Already working with WebmGenerator with the new features, despite the fact that the new subclips renaming saves the final webm with just the inserted tag and not "source filename + tag". Nothing that a good use of Ctrl+C and Ctrl+V can't handle! Thank you very much, it really helps with the boring side of encoding!
