### ISSUE TITLE
Add ability to loop videos for grid merge style

### ISSUE THREAD

**Issue by irlittz** [dfaker/WebmGenerator#18]
Hey, I thought I was doing something wrong for quite a while when using the grid mode, I just intuitively assumed that all clips would loop until the longest clip in the grid played at least once or even up to "Target Length" seconds -- what actually seems to happen is that the video just ends after the duration of the shortest clip. From what I've seen, there are also no filters to loop or repeat slices up to a set duration. Am I missing something?

**Comment by dfaker** [comment]
That's correct the output of the grid mode will end when the shortest clip in the grid ends.
Loop and ping-pong filters are possible but they won't be previewable due to the way the filters mess with the file durations.

**Comment by irlittz** [comment]
By the way, you can get string output from `Popen` if you pass in `universal_newlines=True`, or for newer versions `text=True` too -- that way you wouldn't have to fiddle so much with byte strings from ffmpeg & co.

**Comment by dfaker** [comment]
Yeah thanks, I only just found out about the newer run() method I'll update them all when I remove the global dependencies and factor them out into their own source files.

**Comment by dfaker** [comment]
Release tagged v2.9.0 adds this functionality under the grid loop merge option.

**Comment by cryzed** [comment]
Awesome, thanks!

**Comment by irlittz** [comment]
Agreed, thank you and sorry for the late reply. Nice to see that I'm not the only enjoying this feature.
