### ISSUE TITLE
Unneccesary re-encoding

### ISSUE THREAD

**Issue by dumboluzz** [dfaker/WebmGenerator#19]
The tool does re-encode video, even though video stream should be untouched. If the contraints like max filesize and resolution allow for it, there can be huge performance gains had by just copying the video stream.

Standalone ffmpeg:
`ffmpeg -i INFILE.mp4 -vcodec copy -ss 00:01:00.000 -t 00:00:10.000 OUTFILE.mp4`

**Comment by dfaker** [comment]
If someone wants something as simple as stream copy this probably isn't the right tool for them at all!
I'll consider a pathway for that, perhaps a new merge style that completely hides the majority of options.

**Comment by dumboluzz** [comment]
Well, if you just want to cut small parts out of multiple videos with a ui, this tool seems perfect.

**Comment by dfaker** [comment]
Added in recent commit, will be included in next release.

**Comment by dumboluzz** [comment]
Can any constraints apply to the stream-copy?
For example I may want to still re-encode if the generated file is larger than file size limit.
