### ISSUE TITLE
tkinter EventType

### ISSUE THREAD

**Issue by Pospeno** [dfaker/WebmGenerator#24]
So basically ever since 3.8.7 python has changed how it treads str() for tkinter.EventType 
https://docs.python.org/release/3.8.7/whatsnew/changelog.html

So if you debug with a modern version of python pieces of code like:
`if (str(e.type) in ('ButtonRelease'))`
Will simply not work as indented as `str(e.Type)` it will only return the position in the enum as a string instead of "ButtonRelease".

Instead change it to:
`if (e.type ==tk.EventType.ButtonRelease)`

Start by refactoring this issue in
TimeLineSelectionFrameUI

**Comment by dfaker** [comment]
Thanks for the report, now converted to use tk.EventType.*
