### ISSUE TITLE
Completed video files do not appear inside finalVideos folder on Windows 11

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#30]
So everything seems to work fine but when looking into the finalVideos folder, there's nothing there. 
Which is weird because the play button next to the converted webms in WebmGenerator to preview them once complete, does work, and you can view them.
They really just don't appear in the finalVideos folder and thus are not accessible, which makes WebmGenerator essentially unusable.

I've tried to see if they were marked as hidden files for some reason and they're not. I use a File Explorer replacement called "Files" and I thought it might be an issue with it rather than webmGenerator, so I looked with regular File Explorer too and the result is the same.

Webm completed successfully.
![Screenshot 2021-08-11 210716](https://user-images.githubusercontent.com/29737484/129089115-ba39a685-7347-4c39-a4a4-df073b02fbd3.png)
![Screenshot 2021-08-11 210730](https://user-images.githubusercontent.com/29737484/129089147-26b356ab-ef2c-4a53-8199-545fb17ee60b.png)
Nothing inside finalVideos folder nor tempVideoFiles.
![Screenshot 2021-08-11 210746](https://user-images.githubusercontent.com/29737484/129089156-2481257e-cea2-4db6-b7da-c244475f80db.png)

Specs:
Windows 11 x64 21H2 build 22000.120

**Comment by LolicoreExpress** [comment]
I also used another WebM making program to try and output a webm into the finalVideos folder to see if it was the folder that somehow didn't allow files in, but no, the webm successfully outputed into the finalVideos folder without problem.
So i guess there is a problem with WebmGenerator.

**Comment by dfaker** [comment]
That's a fun one! They must be in a totally different folder.

How are you starting webmGenerator? the folder it creates them in is relative to the current working directory so if you're starting it from a shortcut it may have made a new folder elsewhere next to that shortcut.

**Comment by LolicoreExpress** [comment]
> That's a fun one! They must be in a totally different folder.
> 
> How are you starting webmGenerator? the folder it creates them in is relative to the current working directory so if you're starting it from a shortcut it may have made a new folder elsewhere next to that shortcut.
> 
> Otherwise can you start a command prompt and do:
> 
> ```
> C:
> cd "C:\Program Files\Webm Generator\finalVideos"
> dir
> ```
> 
> Just to double check they're not hidden.

Oooh okay, you were right. I was indeed starting webmGenerator from a shortcut I had made and placed in the folder were the shortcuts for the start menu are located. And yes it was creating folders and outputing in there.
Guess I just have to start it from the original .exe in it's program folder and I'll be fine.
Thank you very much for the quick help. I'm glad it's not broken haha, I use webmGenerator a lot 😊
I'll let you close the issue :)

**Comment by dfaker** [comment]
Cool, you can right click on windows shortcuts and edit the "Start In:" parameter to have them drop wherever you'd like.

**Comment by LolicoreExpress** [comment]
Well it's closed know but just letting you know that changing the "start in" location of the shortcut doesn't work if you want to put back in the original program directory, in my case "C:\Program Files\Webm Generator\finalVideos". It doesn't even let you launch webmgenerator from the shortcut anymore of you do that. Command line window opens for a split second and closes.

But putting "start in" location anywhere else does work as intended. just letting you know in case that's a bug that should be corrected.

**Comment by dfaker** [comment]
I can't reproduce that but assume it's down to windows UAC preventing programs from creating folders or files in the C:\Program Files\ directory, if I recall windows wants you to create all working folders inside the users home directory, one to consider once I shift the output folders to be a configurable option rather than always being relative.

**Comment by LolicoreExpress** [comment]
I can set it to a folder within C:\Program Files and it works.
It's really just setting it back to the original "C:\Program Files\Webm Generator" location that breaks it.
Must be something unique to Windows 11 or my own computer.
