### ISSUE TITLE
The command line window doesn't exit by itself after closing the program if you use the new Windows Terminal

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#31]
It stays open with the following text.

```
2021-09-13 17:16:27,048 [MainThread  ] [INFO ]  CutselectionController destroyed
2021-09-13 17:16:27,125 [MainThread  ] [ERROR]  root.destroy() Exception
Traceback (most recent call last):
  File "K:\WebmGenerator\src\webmGeneratorController.py", line 199, in close_ui
  File "C:\Users\baxter001\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2062, in destroy
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed
2021-09-13 17:16:27,126 [MainThread  ] [INFO ]  DONE
QUIT

[processus terminé avec le code 1]
```

Using the traditional Windows CMD works fine but if you use the new Windows Terminal (Preview version in my case) it doesn't close by itself afterwards.
EDIT: I meant, if you have Windows Terminal enabled to be used as default terminal / command line aplication. On Windows 11 build 22000.184.

**Comment by dfaker** [comment]
Unsure if this is just a thread hanging around and would stay open on both, I'll get the preview and give it a go.

**Comment by dfaker** [comment]
@LolicoreExpress does this happen if you just open it and immediately close without loading a file?

If so it's seemingly not specific to terminal preview, seems to be the thread clean-up that's failing after download+encode, I'll put some elements in to force them closed at shutdown.

**Comment by LolicoreExpress** [comment]
```
2021-09-13 20:58:45,608 [MainThread  ] [INFO ]  Startup.
C:\Program Files\WebmGenerator-win64-3.5.0\lib\src
C:\Program Files\WebmGenerator-win64-3.5.0
Custom profile load 4Chan 4Meg Webm with no Sound.json
Custom profile: {'name': '4chan /tv/ - 4Meg webm with no sound', 'editable': True, 'outputFormat': 'webm:VP8', 'maximumSize': '4.0', 'audioChannels': 'No audio', 'filename': '4Chan 4Meg Webm with no Sound.json'}
Custom profile load 4Chan 4Meg Webm with sound.json
Custom profile: {'name': '4chan /gif/ - 4Meg webm with sound', 'editable': True, 'outputFormat': 'webm:VP8', 'maximumSize': '4.0', 'audioChannels': 'Mono - Medium 64 kbps', 'filename': '4Chan 4Meg Webm with sound.json'}
Custom profile load Discord 8M limit mp4.json
Custom profile: {'name': 'Discord basic 8M mp4', 'editable': True, 'outputFormat': 'mp4:x264', 'maximumSize': '8.0', 'audioChannels': 'Mono - Medium 64 kbps', 'filename': 'Discord 8M limit mp4.json'}
['None', 'Default max quality mp4', 'Sub 4M max quality vp8 webm', 'Sub 100M max quality mp4', 'Sub 8M max quality mp4', '4chan /tv/ - 4Meg webm with no sound', '4chan /gif/ - 4Meg webm with sound', 'Discord basic 8M mp4']
2021-09-13 20:58:54,321 [MainThread  ] [INFO ]  CutselectionController destroyed
2021-09-13 20:58:54,350 [MainThread  ] [ERROR]  root.destroy() Exception
Traceback (most recent call last):
  File "K:\WebmGenerator\src\webmGeneratorController.py", line 238, in close_ui
  File "C:\Users\baxter001\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2304, in destroy
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed
2021-09-13 20:58:54,351 [MainThread  ] [INFO ]  DONE
QUIT

[processus terminé avec le code 1]
```

@dfaker Yeah, same thing. 
I also realised I was still on version 3.0.0, since I hadn't checked in a while and that was just before you added a button to check for updates. 
Anyways, I upgraded to 3.5.0 and the bug is still there, fyi.

**Comment by dfaker** [comment]
Two issues here, one the encoder process wasn't being killed, and for another the property watch on the filter tab wasn't being release, one new one long standing (mostly because I've never killed it during an encode before.)

**Comment by LolicoreExpress** [comment]
Hey, was the following fix in 3.6.0 meant to fix this issue ? Because it still happens for me 🤔 Same thing wether I made an encode or just opened and closed.
> Fix close down issues with needing to wait for encodes to quit before finish and watches not being removed.
I'm on 3.8.1 now.

Terminal window
> 2021-10-01` 19:49:23,173 [MainThread  ] [INFO ]  Startup.
> C:\Program Files\WebmGenerator-win64-3.8.1\lib\src
> C:\Program Files\WebmGenerator-win64-3.8.1
> [WinError 3] Le chemin d’accès spécifié est introuvable: 'resources\\icons'
> Custom profile load 4Chan 4Meg Webm with no Sound.json
> Custom profile: {'name': '4chan /tv/ - 4Meg webm with no sound', 'editable': True, 'outputFormat': 'webm:VP8', 'maximumSize': '4.0', 'audioChannels': 'No audio', 'filename': '4Chan 4Meg Webm with no Sound.json'}
> Custom profile load 4Chan 4Meg Webm with sound.json
> Custom profile: {'name': '4chan /gif/ - 4Meg webm with sound', 'editable': True, 'outputFormat': 'webm:VP8', 'maximumSize': '4.0', 'audioChannels': 'Mono - Medium 64 kbps', 'filename': '4Chan 4Meg Webm with sound.json'}
> Custom profile load Discord 8M limit mp4.json
> Custom profile: {'name': 'Discord basic 8M mp4', 'editable': True, 'outputFormat': 'mp4:x264', 'maximumSize': '8.0', 'audioChannels': 'Mono - Medium 64 kbps', 'filename': 'Discord 8M limit mp4.json'}
> ['None', 'Default max quality mp4', 'Sub 4M max quality vp8 webm', 'Sub 100M max quality mp4', 'Sub 8M max quality mp4', '4chan /tv/ - 4Meg webm with no sound', '4chan /gif/ - 4Meg webm with sound', 'Discord basic 8M mp4']
> 2021-10-01 19:49:32,216 [MainThread  ] [INFO ]  CutselectionController destroyed
> 2021-10-01 19:49:32,266 [MainThread  ] [ERROR]  root.destroy() Exception
> Traceback (most recent call last):
>   File "K:\WebmGenerator\src\webmGeneratorController.py", line 310, in close_ui
>   File "C:\Users\baxter001\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2304, in destroy
> _tkinter.TclError: can't invoke "destroy" command: application has been destroyed
> temp clean up start
> temp clean up end
> 2021-10-01 19:49:32,266 [MainThread  ] [INFO ]  DONE
> QUIT
> [processus terminé avec le code 1]


debug log
> 2021-10-01 19:31:57,327 [MainThread  ] [INFO ]  Startup.
>2021-10-01 19:46:20,567 [MainThread  ] [INFO ]  CutselectionController destroyed
>2021-10-01 19:46:20,606 [MainThread  ] [ERROR]  root.destroy() Exception
>Traceback (most recent call last):
> File "K:\WebmGenerator\src\webmGeneratorController.py", line 310, in close_ui
>  File "C:\Users\baxter001\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2304, in destroy
>_tkinter.TclError: can't invoke "destroy" command: application has been destroyed
>2021-10-01 19:46:20,607 [MainThread  ] [INFO ]  DONE
>2021-10-01 19:49:23,173 [MainThread  ] [INFO ]  Startup.
>2021-10-01 19:49:32,216 [MainThread  ] [INFO ]  CutselectionController destroyed
>2021-10-01 19:49:32,266 [MainThread  ] [ERROR]  root.destroy() Exception
>Traceback (most recent call last):
> File "K:\WebmGenerator\src\webmGeneratorController.py", line 310, in close_ui
>  File "C:\Users\baxter001\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2304, in destroy
>_tkinter.TclError: can't invoke "destroy" command: application has been destroyed
>2021-10-01 19:49:32,266 [MainThread  ] [INFO ]  DONE

**Comment by dfaker** [comment]
Yes, that was addressing that along with another fix.
It does say [processus terminé avec le code 1] so it does seem like the program is returning an exit code to the shell as expected.

This is still windows terminal preview you were seeing this in? I've got it installed and my execution of the same build ends cleanly:
```
...
temp clean up start
temp clean up end
2021-10-01 23:38:14,743 [MainThread  ] [INFO ]  DONE
QUIT
PS K:\WebmGenerator\build\exe.win-amd64-3.9>
```

But I can't set WTP as the system default shell for some reason: this is just via opening up the terminal, navigating to the exe, running it and then quitting, does that method also hang for you?

**Comment by dfaker** [comment]
Looks like this is because I'm returning a non-zero exit code when WMG closes: 
https://github.com/microsoft/terminal/issues/5214 and that's being caught by the 'Profile Termination Behaviour' you have set to 'Close only when process exits  successfully'?

I'll set the return code to zero in the next build to avoid that setting keeping the window open.

**Comment by LolicoreExpress** [comment]
> But I can't set WTP as the system default shell for some reason: this is just via opening up the terminal, navigating to the exe, running it and then quitting, does that method also hang for you?

Yes this is still while using Terminal Preview. It seems that doing it your way, opening a terminal and running webmGenerator from there then closing it, does work like it should.

```
temp clean up start
temp clean up end
2021-10-02 10:12:56,459 [MainThread  ] [INFO ]  DONE
QUIT
PS C:\Program Files\WebmGenerator-win64-3.8.1>
```

and also yes, I have it set to 'Close only when process exits successfully'.

Okay, I'm glad that's sorted out. It wasn't anything major of course but that's still one more thing out of the way. Thank you for your work!

**Comment by dfaker** [comment]
Included in the new release, fingers crossed!

**Comment by LolicoreExpress** [comment]
> Included in the new release, fingers crossed!

It worked ✌️
Thank you.

**Comment by dfaker** [comment]
🎉 wonderful!
