### ISSUE TITLE
[Feature Request] Option to set default folder locations for when file picking

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#32]
What I mean is that the last remembered location for file picking is shared between all file picking scenarios.
So, if I open WebmGenerator and pick a video to open from my Videos folder, when I eventually go and add a filter that requires to pick a font to use, the file picker will open in my previously visited Videos folder. And vice-versa, next time I open WebmGenerator, when I go to open a video file, it'll open in the directory where I picked my font previously. This behavior creates a lot of unnecessary navigating when picking a video or a font in succession, for example.

Suggestion 1, my personaly preferred one: 
Have a setting to set a default folder to open when picking a file depending on the button.
Default location to open for Load Videos, default location to open for fonts...

Suggestion 2:
Make remembering the last folder visited in file picker button specific. As in, Load Videos button will remember its own last visited folder. Font picker for drawtext for example will remember it's own last visited folder as well.

**Comment by dfaker** [comment]
So far I've implemented this as a set of options in the configuration json:
```
"defaultVideoFolder":".",
"defaultImageFolder":".",
"defaultAudioFolder":".",
"defaultFontFolder":".",
"defaultSubtitleFolder":"."
```

The folders will be independent per type, so all Image load buttons will initialise wherever the last image was selected from, but the subtitles for example have an independent default folder.

This has been a minor annoyance for me too, so thanks for suggesting it!

**Comment by LolicoreExpress** [comment]
> So far I've implemented this as a set of options in the configuration json:
> 
> ```
> "defaultVideoFolder":".",
> "defaultImageFolder":".",
> "defaultAudioFolder":".",
> "defaultFontFolder":".",
> "defaultSubtitleFolder":"."
> ```
> 
> The folders will be independent per type, so all Image load buttons will initialise wherever the last image was selected from, but the subtitles for example have an independent default folder.
> 
> This has been a minor annoyance for me too, so thanks for suggesting it!

Awesome, I didn't even know about the config file. This is perfect. Thank you ! 👍

**Comment by dfaker** [comment]
Cool, I'll include this in the next release.
