### ISSUE TITLE
[Feature request] Make the video info at the top of the curently playing cut to be selectable / copyable

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#34]
Yeah, title basically. Sometimes I'm including some of this info, the complete video title most of the time, as text on the video. And it'd be handy to be able to just switch to Cuts tabs and copy it from there. Instead of having to go take it from file explorer / file properties.

**Comment by dfaker** [comment]
Cool, turned into a selectable text entry box on the next release.
