### ISSUE TITLE
Crash when inputting "1" into scaleDown filter

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#35]
That is, if you higlight the text and let's say you changed your mind about down scale and want to type back "1.0" well yeah that will crash. 
On latest v3.6.0.

**Comment by dfaker** [comment]
Errant "2"  typo in the filter, so the default was in fact "1.02" and when it was input as "1" it turned into "12" - which is generally high enough to use up all memory.
