### ISSUE TITLE
[Suggestion] Ways to prevent missclicking on "Apply to all" filter button.

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#36]
I've had the bad experience of missclicking on "Apply to all" filter button and ruining a 50+ batch of webms with different filters each more than one time. Now, that was my fault of course, but I was thinking about how to prevent potential missclicking on that button which is very close to other frequently used buttons. And especially when doing a lot of webms one after the other, it gets repetitive and we are more prone to small errors.

Maybe a confirmation dialog popup on "Apply to all" would be something to consider ? 
Or maybe implementing a way to revert the last changes made à la CTRL+Z ?
Or just moving the button itself away. But that would be weird because while it's probably used less often than it's neighbours, it's still part of that same group of action so it makes sense for it to be there.

I don't know, something to think about maybe :)

**Comment by dfaker** [comment]
Ctrl-z would both need a history setting up, and there'd be a reasonable expectation for it to work elsewhere, I'd like to, but I don't have the strength today!

I'll pop a yes/no popup with an explanation of what the button will do on click.
