### ISSUE TITLE
Text like drawtext is stretched when dealing with stretched 4:3 to 16:9 videos

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#38]
So I'm not super well versed in everything video format and all that, but basically I have these videos that are 1440x1080 but are being displayed as 16:9 (as they should), the only thing is that when using drawtext, the text will also get stretched as you can see.
![Capture d’écran 2021-10-11 192527](https://user-images.githubusercontent.com/29737484/136834357-9ea83434-a1d1-45c2-b151-a88d0e2ca60e.png)
Hopefully it's possible to have the text remain consistent even when dealing with that kind of format / resolution 😊

**Comment by dfaker** [comment]
I suspect the DAR and or SAR are non-square, could you let me know the output of the command:

`ffmpeg -i "videofilepath\videoName.mp4"`

There should be a line in the output like:
`Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 638x360 [SAR 1:1 DAR 319:180], 371 kb/s, 29.97 fps...`

So I can find a similarly squashed file to test with?
