### ISSUE TITLE
Turn off/replace WmG_x suffix

### ISSUE THREAD

**Issue by foralltimes** [dfaker/WebmGenerator#41]
Would be nice if we could either choose an automated tag to title names, or if we could just turn it off.

**Comment by foralltimes** [comment]
Ultimately, it's your project. On the grand scheme of things, it's a minor thing.

**Comment by dfaker** [comment]
Is this causing any practical difficulty for you?

**Comment by foralltimes** [comment]
Not particularly, I usually just use a mass renamer program to get rid of/fix the numbers on clips. The only real problem it brings is when I go back to fix a frame or two from a subclip exported before subsequent clips, and it exports as a new number. Mostly user-generated issues, I only suggested it as it was something that came up a lot for myself.

**Comment by dfaker** [comment]
Ah you mean in the filename. The WmG is gone from there, but an incrementing number remains, as many slice a clip up onto scenes or retry with different filters so something needs to make them unique.

**Comment by foralltimes** [comment]
Oh I see! My apologies, I probably should've caught up version notes before making an issue. Thanks for that.
