### ISSUE TITLE
Constrain video detectors over specific selected periods

### ISSUE THREAD

**Issue by foralltimes** [dfaker/WebmGenerator#43]
Inputting a time frame for where you want scene recognition to occur. Could be helpful if you only need to export clips from a particular area, without needing to scan the entire file.

Sort of related, but I was wondering about arrow keys and if they could be frame back rather than being 5ms. I think it would help ensure files loop between the appropriate start and end without a random scene popping in at the start or end.

**Comment by dfaker** [comment]
Ctrl-shift shifts in single frame increments, you might notice that mpv shifts back to the frame centres after you skip with it using `v` and ctrl-shift you should be able to hit single frames. for the other arrow key end nudging it's using a small timestamp to increment them that should be close to a single frame but isn't precisely the same as the mpv frame-step.

Master should now have those changes (`v`+`arrow keys` to define a blue-dashed range, and the scene detectors will ask you to confirm if you want to use that range in the search), along with some re-ordering of the buttons and an optional 'Toggle fullscreen' in the file menu to make the most of your vertical space.
