### ISSUE TITLE
Pause filter preview

### ISSUE THREAD

**Issue by foralltimes** [dfaker/WebmGenerator#46]
Again, suggestion is the title. Maybe also adjusting speed of the filter preview. I feel like this was something that was in earlier versions that was removed.

Also, is there a way to add a copied filter to another subclip without erasing existing filters?

**Comment by foralltimes** [comment]
NEVERMIND. I clicked on the timeline and you can pause it there. Maybe there could be a bit of ui that emphasises this? I'll keep this up since the second point is still relevant.

**Comment by dfaker** [comment]
I'll add an append filters button in the next release.

The speed control is still there, I seem to recall you're on a quite small layout perhaps you can't see it so I've tried to compress that row down a little more:

![image](https://user-images.githubusercontent.com/35278260/140172761-496bc05e-e66a-4355-9a78-360ea9025748.png)

**Comment by foralltimes** [comment]
Ah I see. Apologies again for these extremely specific issues, and thanks for your assistance.
