### ISSUE TITLE
Subtitles will "stay on" if they are not replaced by a next line

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#47]
I used a SRT format subtitles on a video using the subtitles filter. I made the subs using Aegisub 3.2.2.
Basically, last line of subs currently on display will remain on screen until it is replaced by another line, instead of disappearing at registered end timing.. Essentially, it's like it doesn't recognize the end timing of subtitle lines.
On webmGenerator v.3.11.3

**Comment by dfaker** [comment]
Bug with the zero padding of the end timestamps in the generated .srt  files, now correctly generates end timestamps
