### ISSUE TITLE
If you load a subs file for a cut, but there aren't subs shown during your cut, the webm won't encode

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#49]
Title basically. If you load a subtitle file on a cut during which no subtitles lines appear, it seems that this prevents the cut from encoding.

**Comment by dfaker** [comment]
I'm seeing it correctly generate an empty file which encodes happily, at least with .srt inputs.

**Comment by LolicoreExpress** [comment]
Alright, I can reproduce, Here's more info.

I load up a movie and make one subclip during which there is no dialogue, so no subtitle lines appear.
![Capture d’écran 2021-11-16 181616](https://user-images.githubusercontent.com/29737484/142033791-608a8b18-02b2-44dc-8cf0-96c5da4cda3d.png)

I then apply the subtitle filter and add the .srt subtitle file for the movie.
![Capture d’écran 2021-11-16 181638](https://user-images.githubusercontent.com/29737484/142033899-737e488a-d23a-4eca-a89e-1b17801ab6ce.png)

And try to encode that into a 4MB VP8 Webm. That's where it fails and gets stuck at "50% encoding".
![Capture d’écran 2021-11-16 181531](https://user-images.githubusercontent.com/29737484/142034455-78a3a740-caff-4c4e-9508-9ab39f047aeb.png)
![Capture d’écran 2021-11-16 182333](https://user-images.githubusercontent.com/29737484/142034596-f4415ebf-61ce-40af-bead-ad69ff0cd49d.png)


I know it's kinda stupid anyway since there's really no reason to load a subtitle file on a cut which has no lines of dialogue... but yeah.

**Comment by dfaker** [comment]
Huh, that does complain if it's empty.
Okay, I'll add a dummy line if none have been output.

![BarryLyndon1975REMASTERED1080pBluRayx265-RARBG_2](https://user-images.githubusercontent.com/35278260/142059510-66c7a880-9acc-459d-bcf7-6631f79e7a36.gif)

**Comment by LolicoreExpress** [comment]
Great :)
Thanks.
