### ISSUE TITLE
If a subtitle line is already on screen when a cut starts, it won't display

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#50]
Since english isn't my native tongue, I have a bit of a hard time describing this so I made a little mockup in paint:
![Capture d’écran 2021-11-08 123458](https://user-images.githubusercontent.com/29737484/140735774-d854af57-12ec-4766-ada8-118f9d2f6b92.png)
If a subtitle line is already ongoing across Cut 1 and Cut 2, it won't display on Cut 2. Only Subs Line 2 will display on Cut 2.
You see what I mean ? 🤔

**Comment by LolicoreExpress** [comment]
Actually, no. Hold on. I'm not sure exactly what's wrong with what I'm looking at, give me second xD

**Comment by LolicoreExpress** [comment]
Well, nevermind. I can't really pinpoint what went wrong so I'll keep quiet for now and come back if it happens again and I can identify it precisely...

**Comment by dfaker** [comment]
This is a known issue with ffmpeg, I implemented a custom class to pre-slice the subtitles to keep these small gaps, I'll take a look when I look into the 'section with no subs failing' issue.

**Comment by LolicoreExpress** [comment]
Oh, okay. Thanks !
