### ISSUE TITLE
So this thing is worthless. Team has NO IDEA how to do UI. Boram is 1000x better.

### ISSUE THREAD

**Issue by Innomen** [dfaker/WebmGenerator#51]
Don't like that? Try learning to bake some utility into the UI.

**Comment by dfaker** [comment]
Thank you @Innomen, always happy to get feedback on the UI as that's a much harder refinement process than the blunt code.

I'll close this for now as it doesn't contain any actionable dislikes or suggestions for change, but if you do think of something concrete we can discuss don't be shy about re-opening, I'd be delighted to hear it!
