### ISSUE TITLE
Drag and drop multiple files to "load file" section + other minor suggestions

### ISSUE THREAD

**Issue by foralltimes** [dfaker/WebmGenerator#53]
Title says it all. Purely a minor convenience suggestion. 

Also when playing a file, it might be helpful if the play button switched between play and pause.

Another thing was in the filters tab, maybe having a set of aspect ratios that can be used for crop, or even the ability to save your own crop presets, or other filters. Maybe an export/import filters feature?

Cheers for the program, always impressed with your work.

**Comment by dfaker** [comment]
I too dearly wish the drag and drop where possible into the window but sadly nothing in the UI framework supports that!

The button switch and the preset aspect ratios are both sound ideas though.

For the presets, there are three buttons on the right hand side of the speed control on the filters tab:

![image](https://user-images.githubusercontent.com/35278260/150812080-72341b4d-f387-4369-93aa-463e345065f4.png)

export and import copy and paste the current filter stack to to and from your clipboard as json, the same json can be pasted into a .json file inside the 'filterTemplates' subfolder and they'll appear as dropdown options when you click 'Templates'

**Comment by dfaker** [comment]
@foralltimes added a few aspect ratios to choose from when you right click on the aspect ratio spinner:

```
9:16 - Vertical video
1:1 - Square
4:3 - Standard tv
16:10 - Display or tablet
16:9 - Standard HDTV
2:1 - Superscope
```

Any other ratios you'd find helpful as quick defaults?

**Comment by foralltimes** [comment]
Nope, those are a reasonable and practical selection! Very embarrassed that I didn't notice the export/import JSON. You're 10 steps ahead, as always!

**Comment by dfaker** [comment]
@foralltimes drag and drop turned out to be possible, at least on windows.
