### ISSUE TITLE
Feature Request: Add presets for common resolutions to Scale filter

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#55]
I think most people don't use weird non-standard resolutions, so most the time it'll be the usual 16:9 aspect ratio, 360p / 480p / 720p / 1080p and so on.
Personally, I would appreciate some sort of a drop down menu with the common resolutions listed above just to quickly Scale to one of these without having to type it in everytime.
Of course, that would be while keeping the option to enter custom resolutions.
What do you think?

Also, very quick thing but, how about swapping places for height and width boxes in that filter ? Usually we write width first and height second, so it's kinda weird to have height first and width second here.

**Comment by dfaker** [comment]
I've extended the filter syntax to take an optional list of 'presets', each of these must have a property 'preset_name' but anything else will be used to override the values of the filter by matching on their 'n' name field:

![presets](https://user-images.githubusercontent.com/35278260/154829172-ec0b583b-0694-49e2-9e29-aca2dde38bed.png)

If there's anything else you'd find useful for the scale filter, other than these three in the image, just let me know before the next build!

**Comment by LolicoreExpress** [comment]
That's perfect, exactly what I had in mind. Thanks a lot !
