### ISSUE TITLE
Downloading a video via URL, removing it and downloading again results in download failed everytime

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#58]
And strangely enough it persists even after closing and reopening WebmGenerator.
I can reproduce it reliably. I've tried with videos from instagram, youtube and twitter and it always fails to download a second time.

**Comment by LolicoreExpress** [comment]
Yes that is exactly that. As if the fact that it's already present in the directory prevents it from being downloaded again or "resumed" as you say, I don't know if WebmGenerator just loads the video again from that folder or actually re-downloads and replaces it. Whichever it may be, it seems to not be working 😅

**Comment by dfaker** [comment]
I'll see what flags we can pass to youtube-dlp it's handling all of this.
