### ISSUE TITLE
Can't export a new JSON filter template

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#59]
To be honest I'm not even sure that this is how it works.
But, to create a new json filter template, we're supposed to arrange our filters how we want them and then hit "export json", and it should let me save the json file to the filterTemplates directory, right ?
Because I'm clicking "export json" and nothing is happening.
I thought it might be because I have WebMGenerator located on my C:\ drive and it might not have had permission without being run as admin or something, but running it as admin doesn't change anything.

Or am I completely mistaken about how I'm supposed to create a new template ?

**Comment by dfaker** [comment]
Export and import and copying out of an in from your clipboard.

**Comment by LolicoreExpress** [comment]
Oooh okay ! So I was indeed mistaken. My bad. Thank you.
