### ISSUE TITLE
Numbered subclips + more suggestions

### ISSUE THREAD

**Issue by foralltimes** [dfaker/WebmGenerator#63]
Since the subclips in the filter tab are numbered, it would be helpful if the subclips on the merge tab correlate. Makes exporting specific clips easier than having to count each subclip yourself. 

I was also wondering if there was any benefit to a global filter disable/enable button, maybe on the merge screen. This is likely a personal use case, as I tend to export an unfiltered version of clips, then a second export with filters. This is done easily if I remember to export clips before I go through and add filters, but sometimes i'll either go back and add more subclips, which affects the numbered order of files, or i'll just forget.  

Not sure if I've mentioned this before, but when you disable a subclip's filter and click to the next or previous clip, when you click back to that initial subclip the disabled filters reenable. So if I want to go back and turn off filters, I have to go through individually in one direction, and hope that I spent enough time on the subclip for it to load changes on the merge tab. Again, likely specific issues with my own methods, so no pressure if you disregard. 

Some minor suggestions are less about usage, but I noticed in the filter options, "synchronization" is misspelled. Also on the main github page, available is misspelled in the Join section. Extremely pedantic on my end. 

Thanks for tolerating my posts, your tool is extremely well made and I appreciate your work.

**Comment by dfaker** [comment]
Thanks for using the tool @foralltimes always a pleasure to improve it for users that love it.

For the numbering there's a number Id for each clip internally, I'll show those in both uis.

I'll add a little override post filter in that skips all filters should be no problem.

The disable not being sticky is clearly a bug, I'll make sure they get persisted.

Thanks again for your time and consideration!
