### ISSUE TITLE
Feature request: Add a "Cancel All" button to current encodes screen

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#65]
I have been a couple times in the situation where I just launched the encoding for a big batch of encodes only to realize I messed up a filter on all of them or something, and then had to manually click on "cancel" a hundred times over. Well that wasn't very fun to say the least 😂Anyways, do you think it could be possible to implement something like that ?

**Comment by dfaker** [comment]
Yeah done that a few times myself, done.

**Comment by LolicoreExpress** [comment]
Thanks, much appreciated. 👍
