### ISSUE TITLE
Feature request: Add an "Append to all" button

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#66]
The "Append' feature is great, but sometimes I really wish there was an "Append to all" feature, like there is an "Apply to all" one. It would have saved me lots of time. Many a time I have realized I wanted to add the same filter to all other cuts without overriding what filters they already had, but then I have to do that manually like: "Append, next one, append, next one, append [...]" x145 😭 
Really tedious.

**Comment by dfaker** [comment]
Reasonable in a right click menu under the "Apply to all" button.

**Comment by LolicoreExpress** [comment]
Works for me !

**Comment by dfaker** [comment]
I'd love to know what filters you're using with a collection of that size and complexity to encode!

**Comment by LolicoreExpress** [comment]
Oh nothing fancy, really. 🙂
This time it was just varying Scale, Crop and Draw Text filters.
