### ISSUE TITLE
Precise sub clip timing.

### ISSUE THREAD

**Issue by BuyMyMojo** [dfaker/WebmGenerator#70]
An option to manually enter timing for the start and end of a sub clip would be useful for grabbing specific clips without trying to click and drag exactly where you need.

A little bit of an odd example:
I use [MPV](https://s3.buymymojo.net/ShareX/2022/05/Frames.gif) to find the start and end of clips I want to make because of it's snappy frame by frame progression that also shows the time code at each frame.
Being able to set a sub clip's start and end to exactly `00:11:02.934 - 00:11:27.617` would be a nice level of extra control.

**Comment by BuyMyMojo** [comment]
That is perfect for adding new sub clips thank you!
Being able to edit already created ones without remaking it would be nice too

**Comment by dfaker** [comment]
I'm not sure textual input is needed for adjustments, you can zoom in on the timeline with mousewheel (or ctrl-mousewheel for faster zooming) after having clicked on one of the end handles (the blue or red rectangles with dots) arrow keys (or ctrl+arrrowkeys or ctrl+shift+arrow keys) allow progressively finer steps of a single endpoint all the while displaying a white seek pointer and the timecode down to the fractional second:

![image](https://user-images.githubusercontent.com/35278260/167250945-3b27462c-30db-4798-b550-3735fbe61eb0.png)
