### ISSUE TITLE
Draw text filter seems to be broken on v3.19.0

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#71]
Setting the filter works just fine, but it replaces the actual text with the location of the font used.

This
![Capture d’écran 2022-05-08 194901](https://user-images.githubusercontent.com/29737484/167308829-41ca3629-d60e-4b0f-ae56-3769067fc723.jpg)
becomes this
https://user-images.githubusercontent.com/29737484/167308881-1621880b-8565-49e1-99bd-979fd765961f.mp4

**Comment by dfaker** [comment]
Excellent film choice, just pushed a bugfix release now.

**Comment by LolicoreExpress** [comment]
Thank you 😉
