### ISSUE TITLE
Got a crash when changing audio device

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#72]
I just turned off my speakers (a basic 2 speakers + 1 subwoofer) and then plugged in a pair of earbuds, and that's when it crashed.

I think it's the first time that it happened. I tried reproducing but couldn't. Which leads me to believe that it might be something wrong with my computer and maybe not WebmGenerator 🤔
But I thought I should open an issue anyways, just in case.

This is what the command line window had to say:
```
[ALSOFT] (EE) Failed to initialize audio client: 0x8889000f
[ALSOFT] (EE) Device error: 0x8889000f
[ALSOFT] (WW) Error generated on device 000002891ad637a0, code 0xa001

[processus terminé avec le code 3221225477 (0xc0000005)]
```

on v3.20.0

**Comment by dfaker** [comment]
Thank you, you're right that's all handled inside the client mpv player, I'll see what I can break and pass pack to them.

**Comment by LolicoreExpress** [comment]
Oh okay :D Thanks.

**Comment by dfaker** [comment]
Can't reproduce with a variety of audio device switching methods, even pulling out a USB audio device seems to switch gracefully.
Most likely mpv was in some critical section when this occurred, in any case nothing I can deal with on the python side.
