### ISSUE TITLE
The font used for Japanese characters (and maybe Chinese as well?) is in bold and makes things hard to read

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#73]
The Japanese font used in all parts of the UI is in **bold** and can make things hard to decipher especially at the relatively small font size used in the UI. :)
![Capture d’écran 2022-05-18 175900](https://user-images.githubusercontent.com/29737484/169089130-91c696d3-35f0-4c89-b61f-c7b433184298.jpg)
(same thing in the info bar at the top of the cuts tab, on the filters tab, etc.)

**Comment by dfaker** [comment]
Hmm interesting I'm seeing it work fine locally or Hiragana, Katakana and Kanji, can you paste the text that you're getting the poor rendering with into this issue?

**Comment by dfaker** [comment]
![image](https://user-images.githubusercontent.com/35278260/169116387-4749b794-c4f0-47a8-b7f9-e648aa119700.png)

Yeah, renders fine here, and I'm not overriding the font in any way it's simply the out of the box tkinter font, I'll have a look around to see what that is and make sure it's bundled.

**Comment by LolicoreExpress** [comment]
Okay, thank you :)

**Comment by dfaker** [comment]
Investigated this and it should simply be using the installed "Tahoma" font on your system as the first preference, a pixelwise comparison of the latin text seems to indicate that that's what it's using on your system.

Would you mind trying checking in notepad if Japanese characters render correctly with 8pt Tahoma selected?

**Comment by LolicoreExpress** [comment]
Sure ! I'm away from home for a couple days though and can't check, but I'll do that when I get back.

**Comment by LolicoreExpress** [comment]
Alright, I checked and it renders correctly in Notepad.
![Capture d’écran 2022-07-18 161554](https://user-images.githubusercontent.com/29737484/179531722-2fa3cf6f-96e0-4a04-9f89-55cca422dd08.jpg)

**Comment by LolicoreExpress** [comment]
It's been 2 years I know but better late than never ! Can't tell which build exactly solved this or if that was something with my computer. But anyway it renders fine now. This issue can be closed :)

**Comment by dfaker** [comment]
🙃 Thanks!
