### ISSUE TITLE
Subclip creation doesn't follow subclip length setting correctly anymore

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#76]
Kind of hard to explain but basically, when I set a subclip length at, say, 30 seconds, it doesn't make a 30 seconds subclip but rather makes the subclip be a "percentage" of the length of the video according to the current zoom level on the timeline. Sorry I'm having a hard time explain this correctly in english x)
Maybe a couple pictures will help. An example using a 1h40 film.

Here, the timeline is fully zoomed out, and I create a new subclip, set to be 30 seconds:
![Capture d’écran 2022-05-31 003905](https://user-images.githubusercontent.com/29737484/171065353-aada0d31-e09c-41ed-88ca-a2e0776f9c04.jpg)
Same 30 seconds subclip, but created with the timeline fully zoomed in.
![Capture d’écran 2022-05-31 003931](https://user-images.githubusercontent.com/29737484/171065586-7de91006-f6b9-412d-96db-4fbb8941f25b.jpg)

That's on the just released v3.23.0. I skipped 3.22.0 so I don't know if that was introduced in 22 or 23 😋

**Comment by LolicoreExpress** [comment]
Oh, and to be clear, I'm talking about setting a "Slice Length" and then creating a subclip by right-clicking the timeline and "Add new subclip".

**Comment by dfaker** [comment]
That makes perfect sense, serves me right for relying on the `b` shortcut so often!

**Comment by LolicoreExpress** [comment]
Thanks for the quick fix 👍
