### ISSUE TITLE
Opening a WebmGenerator project file by double clicking on it doesn't work properly.

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#78]
To be more precise, it does open WebmGenerator, but it doesn't load anything.
It also creates temp folders and files at the location of the project file instead of using those in the WebmGenerator install folder.

Here's what the console says:
> 2022-06-05 23:44:16,371 [MainThread  ] [INFO ]  Startup.
> C:\Program Files\WebmGenerator-win64-v3.24.1\lib\src
> C:\Program Files\WebmGenerator-win64-v3.24.1
> C:\Program Files\WebmGenerator-win64-v3.24.1\lib\src
> C:\Program Files\WebmGenerator-win64-v3.24.1
> Load filters from JSON Exception [Errno 2] No such file or directory: 'src\\filterSpecs.json'
> Initial file C:\Users\DOZO\Desktop\un singe en hiver.webgproj
> [WinError 3] Specified path couldn't be found: 'resources\\icons'
> Failed to load player bg image couldn't open ".\resources\playerbg.png": no such file or directory
> cutselectionController loaded
> filterSelectionController loaded
> 'NoneType' object has no attribute 'get'
> composeController loaded
> ['None', 'Default max quality mp4', 'Sub 4M max quality vp8 webm', 'Sub 100M max quality mp4', 'Sub 8M max quality mp4']
> mergeSelectionController loaded

Opening WebmGenerator and then loading the project file from the File menu does work, however.
on v3.24.1

**Comment by dfaker** [comment]
So you have the *.webgproj extension associated with the exe?
Okay, that's not something I expected but should be possible to support.

**Comment by dfaker** [comment]
Will include in next release.

**Comment by LolicoreExpress** [comment]
Yes I had it associated with the .exe.

> Will include in next release.

Thank you very much :)
