### ISSUE TITLE
Saving the project works for subclips but does not remember the filters

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#79]
As title says 😊

log from the command window:
> 2022-06-08 01:13:11,228 [MainThread  ] [INFO ]  Startup.
> C:\Program Files\WebmGenerator-win64-v3.24.1\lib\src
> C:\Program Files\WebmGenerator-win64-v3.24.1
> C:\Program Files\WebmGenerator-win64-v3.24.1\lib\src
> C:\Program Files\WebmGenerator-win64-v3.24.1
> [WinError 3] Specified path couldn't be found: 'resources\\icons'
> cutselectionController loaded
> filter template load: Text
> filterSelectionController loaded
> composeController loaded
> 'NoneType' object has no attribute 'get'
> Custom profile load 4Chan 3Meg Webm with no Sound.json
> Custom profile load: 4chan /tv/ - 3Meg webm with no sound
> Custom profile load 4Chan 4Meg Webm with sound.json
> Custom profile load: 4chan /gif/ - 4Meg webm with sound
> Custom profile load 4Chan 6Meg Webm with sound.json
> Custom profile load: 4chan /wsg/ - 6Meg webm with sound
> Custom profile load Discord 8M limit mp4.json
> Custom profile load: Discord basic 8M mp4
> ['None', 'Default max quality mp4', 'Sub 4M max quality vp8 webm', 'Sub 100M max quality mp4', 'Sub 8M max quality mp4', '4chan /tv/ - 3Meg webm with no sound', '4chan /gif/ - 4Meg webm with sound', '4chan /wsg/ - 6Meg webm with sound', 'Discord basic 8M mp4']
> mergeSelectionController loaded
> {'loadedFiles': ['D:/Videos/FILMS/Un homme qui dort/Un homme qui dort - 1974 - Bernard Queysanne.avi'], 'subclips': {'D:/Videos/FILMS/Un homme qui dort/Un homme qui dort - 1974 - Bernard Queysanne.avi': {'1': [476.3556338028169, 560.32], '2': [781.1502347417841, 843.2042253521126]}}, 'interestMarks': {}, 'subClipCounter': 2}
> tempSeclectedRid None
> self.subClipOrder ['1', '2']
> recaculateFilters setSubclipIndex
> 2022-06-08 01:15:52,214 [MainThread  ] [ERROR]  getCurrentClip Exception
> Traceback (most recent call last):
>   File "K:\WebmGenerator\src\filterSelectionUi.py", line 1999, in getCurrentClip
> TypeError: list indices must be integers or slices, not NoneType
> 2022-06-08 01:15:52,214 [MainThread  ] [ERROR]  getCurrentClip Exception
> Traceback (most recent call last):
>   File "K:\WebmGenerator\src\filterSelectionUi.py", line 1999, in getCurrentClip
> TypeError: list indices must be integers or slices, not NoneType
> recaculateFilters setSubclipIndex
> {'start': 476.3556338028169, 'end': 560.32, 'filename': 'D:/Videos/FILMS/Un homme qui dort/Un homme qui dort - 1974 - Bernard Queysanne.avi', 'filters': [], 'filterexp': '', 'filterexpEncStage': ''}
> {'start': 476.3556338028169, 'end': 560.32, 'filename': 'D:/Videos/FILMS/Un homme qui dort/Un homme qui dort - 1974 - Bernard Queysanne.avi', 'filters': [], 'filterexp': '', 'filterexpEncStage': ''}
> float division by zero

**Comment by dfaker** [comment]
Yet another amazing film choice!

There's code in there for it but it's an imperfect restoration if I recall, behaves strangely over multiple repetitive saves, I'll look at re-enabling it and the encode tab persistence at some point.

**Comment by LolicoreExpress** [comment]
> Yet another amazing film choice!
Hehe thanks. Great minds think alike I suppose 😁

Right, thank you ! It's not urgent or anything. Take all the time you need :)
