### ISSUE TITLE
Error running on linux

### ISSUE THREAD

**Issue by siggines** [dfaker/WebmGenerator#81]
On running setup.py:
File "/home/siggins/.local/lib/python3.10/site-packages/cx_Freeze/executable.py", line 92, in base
    raise ConfigError(f"no base named {name!r} ({name_base!r})")
cx_Freeze.exception.ConfigError: no base named 'console' ('console-cpython-310-x86_64-linux-gnu')

On running webmgenerator.py:
File "/home/siggins/WebmGenerator/src/modalWindows.py", line 29, in <module>
    os.add_dll_directory(basescriptPath)
AttributeError: module 'os' has no attribute 'add_dll_directory'

Help

**Comment by siggines** [comment]
Also, I cannot run the windows edition through wine as I get the error:
main thread is not in main loop

**Comment by dfaker** [comment]
I see it, I'll patch it in the next release.

**Comment by dfaker** [comment]
The master branch should work for you now.
