### ISSUE TITLE
Issue with subtitle handling 

### ISSUE THREAD

**Issue by championofdeath** [dfaker/WebmGenerator#84]
I'd like to make webms of mkv files but sometimes the scene would look better without the subtitles in. Is there any way to disable them during editing that I am missing? Is it something that can be implemented in some way?

Anyway thanks for the awesome tool. Definitely the best out there I love it :)

**Comment by championofdeath** [comment]
I made a mistake I just noticed they get stripped away during the final editing. At least while outputting as VP9 webm. At this point I question if there is an option to eventually toggle them into the final rendering?

**Comment by championofdeath** [comment]
I just noticed it strips subs automatically. Then I tried to mess around and try to include them. I got I need to use the subs filter and load .srt file I can extract from the video with WebmGenerator, but I dont know why it sets a wrong color and a wrong font size.

While I can set the color to what I want it to, the size doesn't change.. Am I doing something wrong?

**Comment by championofdeath** [comment]
![image](https://user-images.githubusercontent.com/44276783/183912005-30b5a317-0101-4806-813f-1c768b480c6b.png)

This is the issue I get: REALLY big subs that don't change with the fontsize and they got automatically set to yellow as color which I later modified. 

![image](https://user-images.githubusercontent.com/44276783/183912201-994ef2fe-addc-4203-8863-a9a8976a9053.png)

Then I just noticed that it works correctly with this Demon Slayer video. Even fileSize 12 is the right one actually. Just had to put white as color. 

Weird even tho the files are both from the same releaser (SubsPlease).

**Comment by championofdeath** [comment]
Tried another releaser for the issued videos but nothing. Still too big.

![image](https://user-images.githubusercontent.com/44276783/183913459-5bd22daa-ba05-4129-82a1-ba2ca4c2b759.png)

**Comment by championofdeath** [comment]
Tried a third anime just in case and it works. From another releaser too.
![image](https://user-images.githubusercontent.com/44276783/183914072-5cd47a5f-c13d-41fd-8a15-0917caaed224.png)

Anyway the file that makes this error:
![image](https://user-images.githubusercontent.com/44276783/183914476-5617c84b-260b-4084-860a-8112a3b3e8f0.png)

Is this one (putting on catbox.moe because git doesnt accept it ( https://files.catbox.moe/y6rgw4.srt ). Keep in mind that it happened both with SubsPlease release, and AWS release, whose subs I put here ( https://files.catbox.moe/y6rgw4.srt ) and both the subs make the issue.

Let me know if there is anything I can do to help you

**Comment by championofdeath** [comment]
Just for the record I downloaded another "famous" tool and put the video inside, added sub filter and rendered and it came out as intended. The same video that produced the issues

**Comment by dfaker** [comment]
Yeah those subs have a hardcoded size in them:

```<font face="Roboto Medium" size="52"> ```

I'll see if there are any options for ignoring that other than editing the text of the .srt itself.

**Comment by championofdeath** [comment]
Thanks for investigating. I'll be waiting to hear from you about this or for a version release. 
And again. Thank's for the awesome tool :)

**Comment by championofdeath** [comment]
Another thing that may help you out:

I've just checked the .srt of Kimetsu No Yaiba EP ( https://files.catbox.moe/q2icl8.srt ) which works fine as you can see in the previous posts I made. And it has also some hard coded size but it seems to work fine even with that..?

`<font face="Roboto Medium" size="26"><i>Rengoku!</i></font>`

Not sure what may be happening here then

**Comment by dfaker** [comment]
> it has also some hard coded size but it seems to work fine even with that..?

It's still hardcoding the size, it just so happens that 26 is a more suitable size for the video than the other video at 52.

**Comment by championofdeath** [comment]
I modified the srt file putting 26 and this is how it showed:
![webmGenerator_2022-08-1016-18-06](https://user-images.githubusercontent.com/44276783/183925106-7e1663b3-9835-4593-88b7-9220fdcd4de2.jpg)

Then I  modified subs file putting size equal as 12 and this is the result. A bit off-put compared to the video, but it shrinked.
![image](https://user-images.githubusercontent.com/44276783/183924880-613730f0-26e9-4631-b91c-aaf9b7731c82.png)

**Comment by dfaker** [comment]
With the most recent release the "Extract .srt subtitles from video file" option will strip those hardcodings from a video or existing subs file.
