### ISSUE TITLE
can't unmute player

### ISSUE THREAD

**Issue by broconut123** [dfaker/WebmGenerator#86]
Running the latest release on linux. The mute button in the player does nothing when clicking on it. 
![image](https://user-images.githubusercontent.com/92729707/184501878-2f9d0144-c978-4cc4-b10c-7d5892e1047d.png)

If you press play after encoding and then closing the mpv player the software crashes "fish: Job 1, 'python webmGenerator.py' terminated by signal SIGSEGV (Address boundary error)".

I've also experienced some cases the software becomes unclickable, not sure what could be triggering it.

**Comment by dfaker** [comment]
Interesting, the mpv OSD shouldn't even show, volume should be fully controlled by the UI slider on the right.

Can you confirm which version of libmpv you have installed?

**Comment by broconut123** [comment]
Used mpv 1:0.34.1-5 at https://archlinux.org/packages/community/x86_64/mpv/
