### ISSUE TITLE
Mono audio track in place of Stereo

### ISSUE THREAD

**Issue by 30secstf** [dfaker/WebmGenerator#87]
Hello, dfaker. Despite having Stereo selected in Merge tab I keep getting mono audio track for every new encode. Tested with a source file that clearly separate both channels.

**Comment by dfaker** [comment]
Just confirmed it works with stereo encoded as expected with mp4 or webm encodes on the most recent release.

Can you confirm the file type of encode and the bitrate you're using?

**Comment by 30secstf** [comment]
I just redid the encodes on a short clip in VP8, VP9, x264, bitrates were 64 and 96 Kb/s, still mono output. I get this somewhere in the command line:

b"\r\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tempVideoFiles\\0_Stereo_-_Left_and_Right_Stereo_Sound_Test-6TWJaFD6_6.5022066805845515_25.03066858037579_aee5115158_1660670295_0.mp4':"
b'\r\n  Metadata:'
b'\r\n    major_brand     : isom'
b'\r\n    minor_version   : 512'
b'\r\n    compatible_brands: isomiso2avc1mp41'
b'\r\n    encoder         : Lavf59.23.100'
b'\r\n  Duration: 00:00:18.55, start: 0.000000, bitrate: 2969 kb/s'
b'\r\n  Stream #0:0[0x1](und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 480x270 [SAR 1:1 DAR 16:9], 2892 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)'
b'\r\n    Metadata:'
b'\r\n      handler_name    : VideoHandler'
b'\r\n      vendor_id       : [0][0][0][0]'
b'\r\n  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 69 kb/s (default)'
b'\r\n    Metadata:'
b'\r\n      handler_name    : SoundHandler'
b'\r\n      vendor_id       : [0][0][0][0]'
b'\r\nStream mapping:'
b'\r\n  Stream #0:0 (h264) -> setpts:default'
b'\r\n  Stream #0:1 (aac) -> concat'
b'\r\n  null:default -> Stream #0:0 (libx264)'
b'\r\n  anull:default -> Stream #0:1 (aac)'

**Comment by 30secstf** [comment]
More details, it's very strange.  I do the encode runs on a headless Windows system using Remote Desktop, v3.30.0 but it happens on a v3.28.0 too (different folders). But I also tested on a v3.28.0 on the other Windows system I use to control the headless one and it's the same behaviour. When in Cuts tab the stereophony works perfectly but every encode, even if it marked as Stereo in the file properties, has mono output (both channels play on both loudspeakers).  Changing only the Mono/Stereo setting in Merge tab produce files of different size but both plays as mono. Also the file relative to the stereo encode run in tempVideoFiles folder play as mono (as does the other one but that's expected).

**Comment by dfaker** [comment]
> Also the file relative to the stereo encode run in tempVideoFiles folder play as mono (as does the other one but that's expected).

This is the crucial part, the temporary encodes are always mono, fixed in master now I'll include it in the next build.
