### ISSUE TITLE
Bitrate constraint mode

### ISSUE THREAD

**Issue by 30secstf** [dfaker/WebmGenerator#88]
The Bitrate constraint mode option under Advanced Encoding Flags seems stuck on Average even if one of the other two is selected.

Feature request: when using the Sequence merge style is would be nice to be able to mute a single subclip. Ideally it would also be nice to use the audio of a clip for another clip (or a sequence, so to have a common audio background). Thanks! ;)

**Comment by dfaker** [comment]
It was being sent to the encoder correctly just not restored correctly in the modal, I'll include that fix in the next release.

**Comment by dfaker** [comment]
@30secstf  With the new audio filters you can apply a volume filter to the individual clips in the filtering tab to achieve your clip muting.

**Comment by 30secstf** [comment]
***@***.***[https://github.com/30secstf] With the new audio filters you can apply a volume filter to the individual clips in the filtering tab to achieve your clip muting.

Hello DepFA,
sorry for the late reply but I check very rarely the e-mail!
Yep, it took a couple of minutes to figure out hot to mute a single clip but I came to the right conclusion, thanks for this specific new feature and for WebmGenerator! While I am at it, how about an easy way to do fade ins and fade outs? I've probably missed something in the filter section but it would be handy to shorten some video in a graceful manner...

Thank you!

Roberto "30secstf"

**Comment by dfaker** [comment]
You're probably looking for the 'Fade at seconds' filter in 'timing and synchronization' has both fade in and fade out modes - but doesn't shorten the clip just fades to a solid colour.

For a Sequence there's the transition style on the encode tab that allows fades between scenes.

**Comment by 30secstf** [comment]
>You're probably looking for the 'Fade at seconds' filter in 'timing and synchronization' has both fade in and fade out modes - but doesn't shorten the clip just fades to a solid colour.
>For a Sequence there's the transition style on the encode tab that allows fades between scenes.

Fade at seconds is what I was looking for but it works only for the video. I was thing more of a Fade for both video and audio at the same time. As for the fade in Sequence merge style, I already use it and it works great, thx!

Roberto "30secstf"
