### ISSUE TITLE
Feature request: Better handling for invalid filenames when encoding

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#90]
I think this is an area that could use a small makeover. The "check" for a valid filename seems to happen way after the encode is launched. Sometimes I launch an encode with an invalid filename (some non-allowed character in there) but it will only cancel the encode after 10 long minutes of encoding depending on what I'm cooking. Which can be a bit of a pain.
So why not have the "check" for a wrong filename happen first and foremmost when launching an encode and telling you right off the bat what's wrong with your filename / what characters were not allowed ? 
That's something that could save a lot of time and minimize mistakes, I think.

So options I was thinking about were the following:
1- Make the check happen -before- starting the encode and stop if filename is invalid
and/or
1- Improve the auto-naming of encodes (it usualy lefts off characters that are actually allowed)
2- Make a tooltip or something appear, that tells you what characters were not allowed in your filename

**Comment by LolicoreExpress** [comment]
And just in general. I have encode with a "/" in the filename, but the program doesn't tell you that the encode failed because the filename had an invalid character in it, so you're just left figuring it out for yourself. Very unfriendly for the average user.

**Comment by dfaker** [comment]
I'll see what I can dig out for validation as there are quite a few edge cases, "/" is an interesting case as the filename is being normalised so that will be behaving as if it expects an additional subfolder.

**Comment by LolicoreExpress** [comment]
Nice, thank you !

**Comment by dfaker** [comment]
The filename entry on the encode tab will now check as far as possible if the filename is creatable after 7425439 it'll still allow you to force using your selected naming but will highlight the field in red if the name fails checks.

**Comment by LolicoreExpress** [comment]
Awesome, that's perfect. Thank you !
