### ISSUE TITLE
Stream Copy produces corrupted video when joining multiple subclips

### ISSUE THREAD

**Issue by LolicoreExpress** [dfaker/WebmGenerator#91]
Joining multiple subclips together using the Stream Copy feature seems to produce a corrupted video. Specifically at the transition between each clip. Have a look.
https://user-images.githubusercontent.com/29737484/191583502-493aec26-f79a-40d2-9fdc-ad666309e0c9.mp4

**Comment by dfaker** [comment]
Yes this is expected, it's a matter of luck (or rather the lack of it) as to how bad this is, I'd not recommend using multiple clips in stream copy unless you feel sufficiently lucky.

**Comment by LolicoreExpress** [comment]
Oh okay haha. Too bad, I was starting to like this feature more and more despite this 😅

**Comment by dfaker** [comment]
It's fast but it doesn't escape the usual 'lossless' downsides of possible joining artefacts and clamping to keyframes.

**Comment by LolicoreExpress** [comment]
I see. Oh well, can't be helped then.

**Comment by LolicoreExpress** [comment]
Lol for some reason my brain did not register the link you put. 
Thanks for the recommandation I'll check it out. I guess this can be closed then ^^
