### ISSUE TITLE
[Request] Use ',' and '.' for precise frame seeking

### ISSUE THREAD

**Issue by FilthyLiquid** [dfaker/WebmGenerator#95]
As the title says, youtube and other media players use it, there doesn't seem to be any way to do it currently.
Also, make the video stay paused when seeking through a video. It's incredibly annoying to have it start playing again when you're trying to get it to start/end where you want it.

**Comment by dfaker** [comment]
More than happy to, and a toggle in for the 'auto-unpause'.

As it stands there's the existing combination ctrl+shift+arrows that steps a frame at a time if you wanted frame precise cuts you can:

- pause with `space`.
- `ctrl+shift+arrows` to the start frame.
- press `v` to start a new selection.
- `ctrl+shift+arrows` to the end frame.
- press `v` to close the selection and turn it into a new subclip.

**Comment by dfaker** [comment]
`,` and `.` are added in as frame seek commands now, will be included in the next release build.
