### ISSUE TITLE
"Open Folder" button doesn't work in v3.35.0

### ISSUE THREAD

**Issue by N6MCA51593** [dfaker/WebmGenerator#96]
Console says "'explorer.exe' is not recognized as an internal or external command, operable program or batch file." Worked as intended in the previous version.

**Comment by dfaker** [comment]
Weird, it's still using the old method of `os.startfile` if that new method fails.

What os are we using?

**Comment by N6MCA51593** [comment]
> What os are we using?

Windows 10 22H2

**Comment by dfaker** [comment]
weird, same, a better failure detection method will be included in the next build.
